import React, { useEffect, useState } from 'react';
import { 
  FileText, 
  Sparkles, 
  TrendingUp, 
  AlertCircle,
  Calendar,
  CheckCircle,
  ChevronRight,
  TrendingDown
} from 'lucide-react';

export const WeeklyReports: React.FC = () => {
  const [reports, setReports] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);
  const [generating, setGenerating] = useState(false);
  const [selectedReport, setSelectedReport] = useState<any | null>(null);

  const loadReports = async () => {
    setLoading(true);
    const token = localStorage.getItem('token');
    const BASE_URL = import.meta.env.VITE_API_URL || 'http://localhost:8000/api/v1';

    try {
      const res = await fetch(`${BASE_URL}/analytics/report`, {
        headers: { 'Authorization': `Bearer ${token}` }
      });
      if (res.ok) {
        const data = await res.json();
        setReports(data);
        if (data.length > 0) {
          setSelectedReport(data[0]);
        }
      }
    } catch (err) {
      console.error('Failed to load weekly reports:', err);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    loadReports();
  }, []);

  const handleGenerateReport = async () => {
    setGenerating(true);
    const token = localStorage.getItem('token');
    const BASE_URL = import.meta.env.VITE_API_URL || 'http://localhost:8000/api/v1';

    try {
      const res = await fetch(`${BASE_URL}/analytics/report`, {
        method: 'POST',
        headers: { 'Authorization': `Bearer ${token}` }
      });
      if (res.ok) {
        const data = await res.json();
        setReports(prev => [data, ...prev]);
        setSelectedReport(data);
      } else {
        alert('Failed to compile weekly report');
      }
    } catch {
      alert('Error generating weekly report');
    } finally {
      setGenerating(false);
    }
  };

  return (
    <div className="space-y-6 font-sans min-h-[85vh]">
      
      {/* Header */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div>
          <h2 className="text-2xl font-bold text-slate-800 dark:text-slate-100 tracking-tight">
            Weekly Progress Reviews
          </h2>
          <p className="text-xs text-slate-400 mt-1">
            recruiter-style progress summaries generated by the Weekly Agent compiling your applications, interview scores, and weaknesses.
          </p>
        </div>
        <button
          onClick={handleGenerateReport}
          disabled={generating}
          className="bg-brand-500 hover:bg-brand-600 text-white font-semibold text-xs px-4 py-2.5 rounded-xl shadow-lg shadow-brand-500/10 flex items-center gap-2 disabled:opacity-50 transition-all"
        >
          {generating ? (
            <>
              <span className="h-4 w-4 border-2 border-white border-t-transparent rounded-full animate-spin" />
              <span>Compiling summary...</span>
            </>
          ) : (
            <>
              <Sparkles className="w-3.5 h-3.5" />
              <span>Generate Progress Review</span>
            </>
          )}
        </button>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6 items-start">
        
        {/* Left Column: Report List Sidebar */}
        <div className="lg:col-span-1 bg-white dark:bg-slate-900 border border-slate-200/60 dark:border-slate-800 p-4 rounded-2xl shadow-sm space-y-3">
          <h3 className="text-xs font-bold text-slate-400 uppercase tracking-widest px-2 mb-2">Historical Reviews</h3>
          
          {loading ? (
            <div className="py-8 text-center">
              <div className="animate-spin rounded-full h-5 w-5 border-2 border-brand-500 border-t-transparent mx-auto" />
            </div>
          ) : reports.length > 0 ? (
            <div className="space-y-2 max-h-[60vh] overflow-y-auto pr-1">
              {reports.map((rep) => (
                <div
                  key={rep.id}
                  onClick={() => setSelectedReport(rep)}
                  className={`p-3.5 rounded-xl border cursor-pointer transition-all flex items-center justify-between ${
                    selectedReport?.id === rep.id
                      ? 'border-brand-500 bg-brand-500/5 text-brand-600 dark:text-brand-450'
                      : 'border-slate-150 dark:border-slate-850 hover:bg-slate-50 dark:hover:bg-slate-800/40 text-slate-700 dark:text-slate-300'
                  }`}
                >
                  <div className="space-y-1">
                    <span className="text-[10px] font-bold block uppercase tracking-wider flex items-center gap-1.5">
                      <Calendar className="w-3.5 h-3.5" />
                      Review Period
                    </span>
                    <span className="text-xs font-semibold block truncate">
                      {new Date(rep.start_date).toLocaleDateString()} - {new Date(rep.end_date).toLocaleDateString()}
                    </span>
                  </div>
                  <ChevronRight className="w-4 h-4 text-slate-400 shrink-0" />
                </div>
              ))}
            </div>
          ) : (
            <p className="text-xs text-slate-400 py-6 text-center">No progress reviews compiled yet. Click the button above to start.</p>
          )}
        </div>

        {/* Right Columns: Active Report scorecard */}
        <div className="lg:col-span-2 space-y-6">
          {selectedReport ? (
            <div className="bg-white dark:bg-slate-900 border border-slate-200/60 dark:border-slate-800 p-6 rounded-2xl shadow-sm space-y-6">
              
              {/* Report Title & Metadata */}
              <div className="flex flex-wrap items-center justify-between gap-4 pb-5 border-b border-slate-100 dark:border-slate-800/80">
                <div className="space-y-1">
                  <span className="text-[10px] font-bold text-brand-500 uppercase tracking-widest block">AI Recruiter Summary</span>
                  <h3 className="font-extrabold text-slate-800 dark:text-slate-100 text-base">
                    Weekly Review Checklist
                  </h3>
                  <span className="text-[11px] text-slate-400 block font-semibold">
                    Generated: {new Date(selectedReport.created_at).toLocaleDateString()}
                  </span>
                </div>
                
                {/* Metrix grid */}
                <div className="flex items-center gap-6">
                  <div className="text-center">
                    <span className="text-[9px] text-slate-400 font-bold uppercase block">Applications</span>
                    <span className="text-sm font-black text-slate-800 dark:text-slate-200 block mt-0.5">{selectedReport.applications_count}</span>
                  </div>
                  <div className="text-center">
                    <span className="text-[9px] text-slate-400 font-bold uppercase block">Readiness</span>
                    <span className="text-sm font-black text-brand-650 dark:text-brand-400 block mt-0.5">{selectedReport.readiness_score}%</span>
                  </div>
                  <div className="text-center">
                    <span className="text-[9px] text-slate-400 font-bold uppercase block">OA Pass Rate</span>
                    <span className="text-sm font-black text-indigo-650 dark:text-indigo-400 block mt-0.5">{selectedReport.oa_success_rate}%</span>
                  </div>
                </div>
              </div>

              {/* Highlights cards */}
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                {selectedReport.biggest_improvement && (
                  <div className="p-4 bg-emerald-500/5 border border-emerald-500/10 rounded-xl space-y-1.5">
                    <span className="text-[9px] font-bold text-emerald-600 dark:text-emerald-400 uppercase tracking-widest flex items-center gap-1.5">
                      <TrendingUp className="w-4 h-4" /> Biggest Improvement
                    </span>
                    <p className="text-xs font-semibold text-slate-700 dark:text-slate-200">{selectedReport.biggest_improvement}</p>
                  </div>
                )}
                {selectedReport.needs_attention && (
                  <div className="p-4 bg-amber-500/5 border border-amber-500/10 rounded-xl space-y-1.5">
                    <span className="text-[9px] font-bold text-amber-600 dark:text-amber-400 uppercase tracking-widest flex items-center gap-1.5">
                      <TrendingDown className="w-4 h-4" /> Attention Required
                    </span>
                    <p className="text-xs font-semibold text-slate-700 dark:text-slate-200">{selectedReport.needs_attention}</p>
                  </div>
                )}
              </div>

              {/* Recruiter Evaluation Text */}
              <div className="space-y-2">
                <span className="text-[10px] text-slate-400 font-bold uppercase tracking-wider block">Recruiter Evaluation Narrative</span>
                <div className="bg-slate-50 dark:bg-slate-900/40 p-5 rounded-xl border border-slate-100 dark:border-slate-800/80 text-xs text-slate-700 dark:text-slate-300 leading-relaxed whitespace-pre-wrap">
                  {selectedReport.report_text}
                </div>
              </div>

              {/* Lists section */}
              <div className="grid grid-cols-1 md:grid-cols-2 gap-6 pt-2 border-t border-slate-100 dark:border-slate-800/60">
                
                {/* Recurring issues */}
                {selectedReport.recurring_issues && selectedReport.recurring_issues.length > 0 && (
                  <div className="space-y-3.5">
                    <span className="text-[10px] text-slate-400 font-bold uppercase tracking-wider block flex items-center gap-1.5">
                      <AlertCircle className="w-3.5 h-3.5 text-rose-500" /> Persistent Gaps
                    </span>
                    <ul className="text-xs text-slate-600 dark:text-slate-400 space-y-2">
                      {selectedReport.recurring_issues.map((issue: string, i: number) => (
                        <li key={i} className="flex items-start gap-2">
                          <span className="h-1.5 w-1.5 rounded-full bg-rose-500 shrink-0 mt-1.5" />
                          <span>{issue}</span>
                        </li>
                      ))}
                    </ul>
                  </div>
                )}

                {/* Recommended focus */}
                {selectedReport.recommended_focus && selectedReport.recommended_focus.length > 0 && (
                  <div className="space-y-3.5">
                    <span className="text-[10px] text-slate-400 font-bold uppercase tracking-wider block flex items-center gap-1.5">
                      <CheckCircle className="w-3.5 h-3.5 text-brand-500" /> Action Target Focus
                    </span>
                    <ul className="text-xs text-slate-600 dark:text-slate-400 space-y-2">
                      {selectedReport.recommended_focus.map((focus: string, i: number) => (
                        <li key={i} className="flex items-start gap-2">
                          <span className="h-1.5 w-1.5 rounded-full bg-brand-500 shrink-0 mt-1.5" />
                          <span>{focus}</span>
                        </li>
                      ))}
                    </ul>
                  </div>
                )}

              </div>

            </div>
          ) : (
            <div className="bg-white dark:bg-slate-900 border border-slate-200/60 dark:border-slate-800 text-center py-24 rounded-2xl flex flex-col items-center justify-center p-6 shadow-sm">
              <FileText className="w-12 h-12 text-slate-300 dark:text-slate-700 mb-3" />
              <h4 className="font-semibold text-slate-700 dark:text-slate-300 text-sm">No review selected</h4>
              <p className="text-xs text-slate-400 max-w-xs mt-1">
                Compile a new review period report to view evaluation metrics and recruiter critiques.
              </p>
            </div>
          )}
        </div>

      </div>

    </div>
  );
};
