import React, { useEffect, useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { 
  FileText, 
  Sparkles, 
  TrendingUp, 
  AlertCircle,
  Calendar,
  CheckCircle,
  ChevronRight,
  TrendingDown
} from 'lucide-react';

export const WeeklyReports: React.FC = () => {
  const [reports, setReports] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);
  const [generating, setGenerating] = useState(false);
  const [selectedReport, setSelectedReport] = useState<any | null>(null);

  const loadReports = async () => {
    setLoading(true);
    const token = localStorage.getItem('token');
    const BASE_URL = import.meta.env.VITE_API_URL || 'http://localhost:8000/api/v1';

    try {
      const res = await fetch(`${BASE_URL}/analytics/report`, {
        headers: { 'Authorization': `Bearer ${token}` }
      });
      if (res.ok) {
        const data = await res.json();
        setReports(data);
        if (data.length > 0) {
          setSelectedReport(data[0]);
        }
      }
    } catch (err) {
      console.error('Failed to load weekly reports:', err);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    loadReports();
  }, []);

  const handleGenerateReport = async () => {
    setGenerating(true);
    const token = localStorage.getItem('token');
    const BASE_URL = import.meta.env.VITE_API_URL || 'http://localhost:8000/api/v1';

    try {
      const res = await fetch(`${BASE_URL}/analytics/report`, {
        method: 'POST',
        headers: { 'Authorization': `Bearer ${token}` }
      });
      if (res.ok) {
        const data = await res.json();
        setReports(prev => [data, ...prev]);
        setSelectedReport(data);
      } else {
        alert('Failed to compile weekly report');
      }
    } catch {
      alert('Error generating weekly report');
    } finally {
      setGenerating(false);
    }
  };

  return (
    <motion.div 
      initial={{ opacity: 0, y: 15 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.4 }}
      className="space-y-8 pb-12 font-sans relative"
    >
      {/* 3D Ambient backdrop Blob */}
      <div className="absolute -top-12 right-1/4 w-96 h-96 bg-vermilion/5 rounded-full blur-3xl pointer-events-none animate-blob"></div>

      {/* Header */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div>
          <h2 className="text-xl font-bold tracking-widest text-cocoa font-serif uppercase">
            Weekly Progress Reviews
          </h2>
          <p className="text-xs text-cocoa/60 mt-2 max-w-lg leading-relaxed font-semibold uppercase tracking-wider">
            Recruiter-style progress summaries generated by the Weekly Agent compiling your applications, interview scores, and DSA topic weaknesses.
          </p>
        </div>
        <button
          onClick={handleGenerateReport}
          disabled={generating}
          className="bg-vermilion hover:bg-vermilion/90 text-white font-bold text-xs px-5 py-3 rounded-[1.2rem] shadow-lg shadow-vermilion/10 flex items-center gap-2 disabled:opacity-50 transition-all active:scale-95 animate-pulse-subtle"
        >
          {generating ? (
            <>
              <span className="h-4 w-4 border-2 border-white border-t-transparent rounded-full animate-spin" />
              <span>Compiling summary...</span>
            </>
          ) : (
            <>
              <Sparkles className="w-3.5 h-3.5 text-cocoa" />
              <span>Generate Progress Review</span>
            </>
          )}
        </button>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6 items-start">
        
        {/* Left Column: Report List Sidebar */}
        <div className="lg:col-span-1 bg-white border border-cocoa/10 p-4 rounded-[1.5rem] shadow-md backdrop-blur-md space-y-4">
          <h3 className="text-[10px] font-bold text-cocoa/40 uppercase tracking-widest px-2 mb-1">Historical Reviews</h3>
          
          {loading ? (
            <div className="py-8 text-center">
              <div className="relative w-8 h-8 mx-auto">
                <div className="absolute inset-0 rounded-full border-3 border-vermilion/25"></div>
                <div className="absolute inset-0 rounded-full border-3 border-vermilion border-t-transparent animate-spin"></div>
              </div>
            </div>
          ) : reports.length > 0 ? (
            <div className="space-y-3 max-h-[60vh] overflow-y-auto pr-1">
              {reports.map((rep) => (
                <div
                  key={rep.id}
                  onClick={() => setSelectedReport(rep)}
                  className={`p-4 rounded-[1.2rem] border cursor-pointer transition-all flex items-center justify-between ${
                    selectedReport?.id === rep.id
                      ? 'border-vermilion bg-vermilion/5 text-vermilion'
                      : 'border-cocoa/10 bg-sand hover:bg-sand/80 text-cocoa dark:border-cocoa/10 dark:bg-sand'
                  }`}
                >
                  <div className="space-y-1">
                    <span className="text-[9px] font-bold block uppercase tracking-wider flex items-center gap-1.5 text-cocoa/40">
                      <Calendar className="w-3.5 h-3.5" />
                      Review Period
                    </span>
                    <span className="text-xs font-bold block truncate">
                      {new Date(rep.start_date).toLocaleDateString()} — {new Date(rep.end_date).toLocaleDateString()}
                    </span>
                  </div>
                  <ChevronRight className="w-4 h-4 text-cocoa/40 shrink-0 dark:text-cocoa/40" />
                </div>
              ))}
            </div>
          ) : (
            <p className="text-xs text-cocoa/50 py-6 text-center">No progress reviews compiled yet. Click the button above to start.</p>
          )}
        </div>

        {/* Right Columns: Active Report scorecard */}
        <div className="lg:col-span-2 space-y-6">
          <AnimatePresence mode="wait">
            {selectedReport ? (
              <motion.div 
                key={selectedReport.id}
                initial={{ opacity: 0, scale: 0.98 }}
                animate={{ opacity: 1, scale: 1 }}
                exit={{ opacity: 0 }}
                className="bg-white border border-cocoa/10 p-6 rounded-[1.5rem] shadow-md backdrop-blur-md space-y-6"
              >
                
                {/* Report Title & Metadata */}
                <div className="flex flex-wrap items-center justify-between gap-4 pb-5 border-b border-cocoa/10 dark:border-cocoa/10">
                  <div className="space-y-1">
                    <span className="text-[9px] font-bold text-vermilion bg-vermilion/10 border border-vermilion/20 px-2 py-0.5 rounded-full uppercase tracking-wider">AI Recruiter Summary</span>
                    <h3 className="font-bold text-cocoa text-base mt-2.5 dark:text-cocoa font-serif">
                      Weekly Review Checklist
                    </h3>
                    <span className="text-[10px] text-cocoa/50 block font-semibold dark:text-cocoa/40">
                      Generated: {new Date(selectedReport.created_at).toLocaleDateString()}
                    </span>
                  </div>
                  
                  {/* Metric grid */}
                  <div className="flex items-center gap-6">
                    <div className="text-center">
                      <span className="text-[9px] text-cocoa/50 font-bold uppercase block dark:text-cocoa/40">Applications</span>
                      <span className="text-sm font-bold text-cocoa block mt-1 dark:text-zinc-200 font-serif">{selectedReport.applications_count}</span>
                    </div>
                    <div className="text-center">
                      <span className="text-[9px] text-cocoa/50 font-bold uppercase block dark:text-cocoa/40">Readiness</span>
                      <span className="text-sm font-bold text-vermilion block mt-1 font-serif">{selectedReport.readiness_score}%</span>
                    </div>
                    <div className="text-center">
                      <span className="text-[9px] text-cocoa/50 font-bold uppercase block dark:text-cocoa/40">OA Success</span>
                      <span className="text-sm font-bold text-emerald-600 block mt-1 font-serif">{selectedReport.oa_success_rate}%</span>
                    </div>
                  </div>
                </div>

                {/* Highlights cards */}
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  {selectedReport.biggest_improvement && (
                    <div className="p-4 bg-emerald-500/5 border border-emerald-500/10 rounded-[1.2rem] space-y-1.5">
                      <span className="text-[9px] font-bold text-emerald-700 uppercase tracking-widest flex items-center gap-1.5">
                        <TrendingUp className="w-4 h-4" /> Biggest Improvement
                      </span>
                      <p className="text-xs font-semibold text-cocoa/90 dark:text-zinc-200">{selectedReport.biggest_improvement}</p>
                    </div>
                  )}
                  {selectedReport.needs_attention && (
                    <div className="p-4 bg-vermilion/5 border border-vermilion/10 rounded-[1.2rem] space-y-1.5">
                      <span className="text-[9px] font-bold text-vermilion uppercase tracking-widest flex items-center gap-1.5">
                        <TrendingDown className="w-4 h-4" /> Attention Required
                      </span>
                      <p className="text-xs font-semibold text-cocoa/90 dark:text-zinc-200">{selectedReport.needs_attention}</p>
                    </div>
                  )}
                </div>

                {/* Recruiter Evaluation Text */}
                <div className="space-y-2">
                  <span className="text-[9px] text-cocoa/50 font-bold uppercase tracking-wider block dark:text-cocoa/40">Recruiter Evaluation Narrative</span>
                  <div className="bg-sand p-5 rounded-[1.2rem] border border-cocoa/10 text-xs text-cocoa/70 leading-relaxed whitespace-pre-wrap dark:bg-cocoa/20 dark:border-cocoa/10 dark:text-cocoa/60">
                    {selectedReport.report_text}
                  </div>
                </div>

                {/* Lists section */}
                <div className="grid grid-cols-1 md:grid-cols-2 gap-6 pt-5 border-t border-cocoa/10 dark:border-cocoa/10">
                  
                  {/* Recurring issues */}
                  {selectedReport.recurring_issues && selectedReport.recurring_issues.length > 0 && (
                    <div className="space-y-3.5">
                      <span className="text-[9px] text-cocoa/50 font-bold uppercase tracking-wider block flex items-center gap-1.5 dark:text-cocoa/40">
                        <AlertCircle className="w-3.5 h-3.5 text-vermilion" /> Persistent Gaps
                      </span>
                      <ul className="text-xs text-cocoa/70 space-y-2 dark:text-cocoa/60">
                        {selectedReport.recurring_issues.map((issue: string, i: number) => (
                          <li key={i} className="flex items-start gap-2">
                            <span className="h-1.5 w-1.5 rounded-full bg-vermilion shrink-0 mt-1.5" />
                            <span>{issue}</span>
                          </li>
                        ))}
                      </ul>
                    </div>
                  )}

                  {/* Recommended focus */}
                  {selectedReport.recommended_focus && selectedReport.recommended_focus.length > 0 && (
                    <div className="space-y-3.5">
                      <span className="text-[9px] text-cocoa/50 font-bold uppercase tracking-wider block flex items-center gap-1.5 dark:text-cocoa/40">
                        <CheckCircle className="w-3.5 h-3.5 text-vermilion" /> Action Target Focus
                      </span>
                      <ul className="text-xs text-cocoa/70 space-y-2 dark:text-cocoa/60">
                        {selectedReport.recommended_focus.map((focus: string, i: number) => (
                          <li key={i} className="flex items-start gap-2">
                            <span className="h-1.5 w-1.5 rounded-full bg-vermilion shrink-0 mt-1.5" />
                            <span>{focus}</span>
                          </li>
                        ))}
                      </ul>
                    </div>
                  )}

                </div>

              </motion.div>
            ) : (
              <div className="bg-white border border-cocoa/10 text-center py-24 rounded-[1.5rem] flex flex-col items-center justify-center p-8 shadow-lg">
                <FileText className="w-12 h-12 text-cocoa/30 mb-4" />
                <h4 className="font-bold text-cocoa text-sm uppercase tracking-wider font-serif">No review selected</h4>
                <p className="text-[11px] text-zinc-455 max-w-xs mt-2.5 leading-relaxed font-semibold uppercase tracking-wider">
                  Compile a new review period report to view evaluation metrics and recruiter critiques.
                </p>
              </div>
            )}
          </AnimatePresence>
        </div>

      </div>

    </motion.div>
  );
};

